### ISSUE TITLE
Syntax highlighting in 0.101.0 broken

### ISSUE THREAD

**Issue by calebmer** [atom/language-javascript#258] opened 2015-11-17 22:53 UTC
Just updated `language-javascript` and all the syntax highlighting is broken. I use ES7 and JSX, so I am using the most recent version of this package. Here is an image:

![screen shot 2015-11-17 at 5 50 12 pm](https://cloud.githubusercontent.com/assets/8282507/11227409/ce3c5a14-8d53-11e5-9be5-26955578784d.png)

Everything is red and blue and incorrectly/inconsistently so. Also note line 40 where the `default` keyword is in red. This update is definitely not aesthetically pleasing and in no way consistent. Is there a way to downgrade?

**PS**: Also, are there plans of supporting JSX?

**Comment by 50Wliu** [comment] 2015-11-17 23:19
What version did you update from?  In addition, what syntax theme are you using (it seems like One Dark, but I just want to make sure), and do you have any customizations in your local stylesheet?  You can downgrade by doing `apm install language-javascript@0.xyz.0`.

I don't believe there are any plans to support JSX, since it is already well-supported by language-babel and language-jsx.

/cc @simurai @MaximSokolov

**Comment by 50Wliu** [comment] 2015-11-17 23:23
Most of the new highlighting you're seeming seems to be because of #242.  I'm aware there's inconsistencies - we're still trying to improve support.  In particular, it looks like the `query` block has been mis-tokenized.  Can you please paste a code snippet here that reproduces that bug so we can take a look at it?  Thanks.

**Comment by simurai** [comment] 2015-11-18 02:31
Here the second part of the example:

```js
class Database {
  query(query, values) {
    let {client} = this
    return (
      client
      .then(client =>
        new Promise((resolve, reject) => (
          client.query(query, values, (error, result) => {
            if (error) { return reject(error) }
            resolve(result)
          })
        ))
      )
    )
  }
}

export default Database
```

And screenshot before vs after:

![screen shot 2015-11-18 at 10 19 30 am](https://cloud.githubusercontent.com/assets/378023/11230092/0d42947c-8ddf-11e5-905d-dcfe42cbe00a.png)

----------

> Everything is red and blue

Yeah, in that example it does feel a bit like too much coloring. Most of the red seems to get styled with `.variable {}`. So we could reset it in themes with:

```
.variable.other.argument {
    color: @syntax-text-color;
  }
```

And to reset the blue https://github.com/atom/language-javascript/pull/242#issuecomment-153007321. 

But next to the core themes, there are probably 100s of community themes that are affected too. Well, all that do `.variable { color: some-color; }`. So maybe another option is to not use the `.variable` scope, but something else instead. Not sure what though. Or just `other argument js`? Then no changes to themes are necessary, but themes or in style.less it's still possible to style them.. it would be opt-in instead of opt-out.

@MaximSokolov what do you think about that? I know `variable other argument` would be more correct, but just to minimize the impact and still make it possible to style for those who want.

**Comment by 50Wliu** [comment] 2015-11-18 02:40
When we (eventually) add tokenization for regular variables (eg `var variable1`), what will happen then?  There'll really be no avoiding using `.variable`.

**Comment by simurai** [comment] 2015-11-18 02:58
Hmm.. I see. Well, I somewhat agree that languages should have the freedom to do anything they want without having to check how/if it affects themes. If something looks visually too noisy it's the theme's responsibility to restyle it. Well, it's easier said than persuade all theme authors. :sweat_smile:

**Comment by MaximSokolov** [comment] 2015-11-18 16:30
> note line 40 where the `default` keyword is in red.

See [#237 (comment)](https://github.com/atom/language-javascript/pull/237#issuecomment-146006014)

> Everything is **red** and blue

It's a syntax-theme specific issue. "One Dark Syntax" color all variables like that (see variables in PHP). Most of variables just aren't tokenized
Related: atom/atom#9562

> Everything is red and **blue**

I agree that function/method calls should be same color as function name in delcaration.
I used `entity.name.function` because I think we should reuse [standart TextMate scopes](http://manual.macromates.com/en/language_grammars#naming_conventions):
`meta.method-call`, `meta.function-call` (provide context) + `entity.name.function`

It can be `entity.other.function-call`, `entity.other.method-call` though
> it looks like the `query` block has been tokenized incorrectly

#260

**Comment by calebmer** [comment] 2015-11-18 22:40
I can confirm that I am using both One Dark UI theme and One Dark syntax theme. Also, I'm not entirely sure what I upgraded from, but I've had `language-javascript` installed as a community package for a while now so I can say, semi-confidently, two versions before `0.101.1` (so `0.100.0` or `0.99.0` I think).

Here is the entire file and another one having problems:

```js
import Postgres from 'pg'

class Database {
  config = null
  client = null

  constructor(config) {
    this.config = config
  }

  connect() {
    let {config} = this

    this.client = new Promise((resolve, reject) => {
      Postgres.connect(config, (error, client) => {
        if (error) { return reject(error) }
        resolve(client)
      })
    })

    return this.client.then(() => null)
  }

  query(query, values) {
    return (
      this.client
      .then(client =>
        new Promise((resolve, reject) => (
          client.query(query, values, (error, result) => {
            if (error) { return reject(error) }
            resolve(result)
          })
        ))
      )
    )
  }
}

export default Database

```

Another broken file, weirdness happens around the anonymous middleware function:

```js
import ReactDOMServer from 'react-dom/server'
import App from '../app'

App.use(function (req, res, next) {
  Object.assign(res, {
    render(nodes) {
      if (!Array.isArray(nodes)) { nodes = [nodes] }
      let markup = ''
      nodes.forEach(node => markup += ReactDOMServer.renderToStaticMarkup(node))
      res.write(markup)
    }
  })

  next()
})
```

My custom css:

```less
@import 'colors';

atom-text-editor::shadow {
  .operator {
    color: @hue-3;
  }
}
```

**Comment by lukeapage** [comment] 2015-11-19 14:45
My syntax highlighting is broken after upgrading from 100 to 101.1 - its breaking when comments contain '
e.g.
```
            _.forOwn(this.subscriptionList, function(priceSub) {

                if (oldFilter == null) { // we don't know what the previous filter was
                    if (newFilter == 'all') { // ? -> all
                        //resume all
```
![image](https://cloud.githubusercontent.com/assets/309321/11273610/191138ba-8ecc-11e5-9281-04baedc442ee.png)

**Comment by MaximSokolov** [comment] 2015-11-19 15:03
@lukeapage it's fixed on `master`. Will be available in v102

**Comment by lukeapage** [comment] 2015-11-19 15:06
Great thanks

**Comment by xpepermint** [comment] 2016-03-16 21:38
Tis is it yes... This https://github.com/atom/language-javascript/issues/258 is also related.

**Comment by 50Wliu** [comment] 2016-08-30 02:17
Assuming fixed, so closing.  Feel free to comment here if it's still an issue.

The "too much red" issue is not one that can be solved by language-javascript as in this case we're actually adding the correct scopes.

**Closed by 50Wliu** 2016-08-30 02:17 UTC
Labels: bug, feedback, more-information-needed
