### ISSUE TITLE
Syntax highlighting breaks on funky regular expressions

### ISSUE THREAD

**Issue by shawninder** [atom/language-javascript#204] opened 2015-08-24 14:42 UTC
I don't know what is causing the problem, but the syntax highlighting messes up after this line (the text that follows is orange all the way down until the next `/`):

```js
var re = /(url\()(?:\s*(?!https?:\/\/|data:)((?:[^"'()\\]|\\(?:[^\n0-9a-fA-F]|[0-9a-fA-F]{1,6}\s?))*)\s*|\s*"(?!https?:\/\/|data:)((?:[^"\\\n]|\\(?:[^\n0-9a-fA-F]|[0-9a-fA-F]{1,6}\s?)|\\\n)*)"\s*|\s*'(?!https?:\/\/|data:)((?:[^'\\\n]|\\(?:[^\n0-9a-fA-F]|[0-9a-fA-F]{1,6}\s?)|\\\n)*)'\s*)(\))/gi
```

I realize how ugly that line is, but it is correct. I know this because Sublime Text doesn't exhibit the syntax highlighting problem and also because all the tests are passing. If you're curious, this matches the urls in CSS files.

Since Sublime Text correctly syntax highlights this, perhaps you can look up how it's done there and see what the difference is with what you're doing here?

**Comment by shawninder** [comment] 2015-08-24 14:51
In the meantime, I found a workaround:

All I need to do is add the following line immediately after the problematic one:
`/// Fix syntax highlighting for atom`. The first slash "closes" the regexp, the other ones start a comment, and everything is fine after that.

Of course that creates a problem with my linter (standardjs) which requires comments to be followed by a space or tab. So to get both fixed simultaneously, I ended up using:

`// // Fix syntax highlighting for atom`

**Comment by 50Wliu** [comment] 2015-08-24 22:44
I can't seem to reproduce this using Atom 1.0.7 (other than the syntax highlighting breaking for that line only which is tracked at atom/atom#1667.  In addition, Github also seems to be highlighting everything correctly.

What Atom version are you on?  If on 1.0.7, can you reproduce this in safe mode (`atom --safe`)?  Thanks.

**Comment by shawninder** [comment] 2015-08-25 08:02
I also have 1.0.7. Same behaviour in safe mode. But apparently the comment before this line is also playing a role here.. Here is the smallest file I can produce that exhibits the problem:

```// var re = /(url\()(?:\s*(?!https?:\/\/|data:)((?:[^"'()\\]|\\(?:[^\n0-9a-fA-F]|[0-9a-fA-F]{1,6}\s?))*)\s*|\s*"(?!https?:\/\/|data:)((?:[^"\\\n]|\\(?:[^\n0-9a-fA-F]|[0-9a-fA-F]{1,6}\s?)|\\\n)*)"\s*|'\s*(?!https?:\/\/|data:)((?:[^'\\\n]|\\(?:[^\n0-9a-fA-F]|[0-9a-fA-F]{1,6}\s?)|\\\n)*)\s*'\s*)(\))/gi
var re = /(url\()(?:\s*(?!https?:\/\/|data:)((?:[^"'()\\]|\\(?:[^\n0-9a-fA-F]|[0-9a-fA-F]{1,6}\s?))*)\s*|\s*"(?!https?:\/\/|data:)((?:[^"\\\n]|\\(?:[^\n0-9a-fA-F]|[0-9a-fA-F]{1,6}\s?)|\\\n)*)"\s*|\s*'(?!https?:\/\/|data:)((?:[^'\\\n]|\\(?:[^\n0-9a-fA-F]|[0-9a-fA-F]{1,6}\s?)|\\\n)*)'\s*)(\))/gi

console.log("Colors are wrong here")
```

**Comment by pchaigno** [comment] 2015-08-25 09:17
GitHub is also using this grammar for JavaScript highlighting (see [github/linguist](https://github.com/github/linguist)) and it looks fixed:
```js
// var re = /(url\()(?:\s*(?!https?:\/\/|data:)((?:[^"'()\\]|\\(?:[^\n0-9a-fA-F]|[0-9a-fA-F]{1,6}\s?))*)\s*|\s*"(?!https?:\/\/|data:)((?:[^"\\\n]|\\(?:[^\n0-9a-fA-F]|[0-9a-fA-F]{1,6}\s?)|\\\n)*)"\s*|'\s*(?!https?:\/\/|data:)((?:[^'\\\n]|\\(?:[^\n0-9a-fA-F]|[0-9a-fA-F]{1,6}\s?)|\\\n)*)\s*'\s*)(\))/gi
var re = /(url\()(?:\s*(?!https?:\/\/|data:)((?:[^"'()\\]|\\(?:[^\n0-9a-fA-F]|[0-9a-fA-F]{1,6}\s?))*)\s*|\s*"(?!https?:\/\/|data:)((?:[^"\\\n]|\\(?:[^\n0-9a-fA-F]|[0-9a-fA-F]{1,6}\s?)|\\\n)*)"\s*|\s*'(?!https?:\/\/|data:)((?:[^'\\\n]|\\(?:[^\n0-9a-fA-F]|[0-9a-fA-F]{1,6}\s?)|\\\n)*)'\s*)(\))/gi

console.log("Colors are wrong here")
```

**Comment by shawninder** [comment] 2015-08-25 09:19
@pchaigno Have you also tried it in atom?

**Comment by pchaigno** [comment] 2015-08-25 09:24
@shawninder Yep, just did (with last Atom version on Ubuntu):
![atom_js_bug](https://cloud.githubusercontent.com/assets/1764210/9463266/dd88cbe4-4b1b-11e5-8d27-40e2000b3a83.png)

**Comment by shawninder** [comment] 2015-08-25 12:10
This is strange... I'm on Mac OSX 10.10.5, but I wouldn't expect that to change anything... @50Wliu Any luck reproducing this?

**Comment by 50Wliu** [comment] 2015-08-25 12:45
Well this is strange.  I can repro this with the comment as well now.

**Comment by shawninder** [comment] 2015-08-25 12:56
@pchaigno Do you have any packages that might be solving this for you?

**Comment by 50Wliu** [comment] 2015-08-25 13:01
Yeah, it'd be great if you two could both paste the output of `apm list --installed` (or, preferably, reproduce using `atom --safe`) :smile:.

Just checked and I can still repro in safe mode.

**Comment by shawninder** [comment] 2015-08-25 13:06
I also reproduced this in safe mode.
```
$ apm list --installed
/Users/shawn/.atom/packages (13)
├── coffee-compile@0.18.0
├── docs-snippets@0.8.0
├── editorconfig@1.1.1
├── git-plus@5.4.6
├── highlight-selected@0.10.1
├── linter@1.4.3
├── linter-js-standard@2.5.0
├── merge-conflicts@1.3.5
├── monokai@0.18.0
├── pretty-json@0.4.1
├── script@2.26.4
├── toggle-quotes@0.11.3
└── tree-view-git-status@0.1.2
```

**Comment by pchaigno** [comment] 2015-08-25 14:51
> Do you have any packages that might be solving this for you?

@shawninder Nop, fresh install!

**Comment by pchaigno** [comment] 2015-09-07 12:40
Hm... I can reproduce now (just reinstalled Ubuntu and Atom). Weird.

**Comment by 50Wliu** [comment] 2015-11-05 16:32
Ok, I'm pretty sure this is a duplicate of atom/atom#1667, so closing in favor of that.

**Closed by 50Wliu** 2015-11-05 16:32 UTC
Labels: more-information-needed
