### ISSUE TITLE
Highlighting breaks on list of functions

### ISSUE THREAD

**Issue by krrg** [atom/language-javascript#384] opened 2016-07-06 23:16 UTC
![screenshot from 2016-07-06 17 10 10](https://cloud.githubusercontent.com/assets/8496492/16637598/7626e640-439d-11e6-825b-0887c45ec482.png)

In Atom 1.8.0 and language-javascript 0.110.0, highlighting breaks inside an array of function calls on a single line. For example, in

```[a(), b(), c(), d(), e(), f(), g(), h(), j(), k(), l(), m(), n(), o(), p(), q(), r(), s(), t(), u(), v()]```

the `v()` is not highlighted as a function call like the rest of them are.

**Comment by Victorystick** [comment] 2016-07-09 21:17
This also looks to be a duplicate of atom/atom#1667.

**Comment by 50Wliu** [comment] 2016-07-15 11:21
Thanks @Victorystick.

**Closed by 50Wliu** 2016-07-15 11:21 UTC
