### ISSUE TITLE
Constants no longer marked

### ISSUE THREAD

**Issue by adamreisnz** [atom/language-javascript#597] opened 2018-09-20 23:11 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Constants and constant properties (all caps) are no longer marked as constants in the scope.

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/490562/45851355-93f34700-bd8e-11e8-886d-1da680d130b8.png)

![image](https://user-images.githubusercontent.com/490562/45851437-09f7ae00-bd8f-11e8-99c0-aee1e6eb0bff.png)

**Expected behavior:** [What you expect to happen]
Scopes at cursor should be constant and for the constants and constant properties to have correct syntax highlighting.

**Actual behavior:** [What actually happens]

All syntax highlighting for constants is gone, scope is reduced to `source.js`.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

Atom    : 1.32.0-nightly13
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.0-nightly13
python 2.7.10
git 2.14.1

OS X

### Other information
Last worked correctly in Atom 1.32 nightly 6 iirc.

**Comment by Arcanemagus** [comment] 2018-09-20 23:21
With this code:
```js
const foo = {};
foo.BAR = 42;
console.log(foo.BAR);
```

I'm unable to reproduce this on `1.32.0-dev-7d1542298` (should be from around the same time as `-nightly13`):
![2018-09-20_16-18-18](https://user-images.githubusercontent.com/427137/45851666-f3027e80-bcf0-11e8-95b3-29b7b5146810.gif)

Both TextMate and Tree-sitter show the same scope for me, could you elaborate on what the issue is as your screenshots don't seem to be showing the same bits of code.

**Comment by adamreisnz** [comment] 2018-09-20 23:21
Also incorrectly marking constants as `meta.class` now:

![image](https://user-images.githubusercontent.com/490562/45851716-71fac400-bd90-11e8-8fce-b987dd6d280c.png)

These used to be marked as constants.

**Comment by adamreisnz** [comment] 2018-09-20 23:30
Unchecking the Tree Sitter parser checkbox fixed the issue.

**Comment by Arcanemagus** [comment] 2018-09-21 17:20
Interesting, it looks like the toggling of Tree-sitter parsers wasn't working for me the first few times I toggled it, so in the above GIF I posted it was simply using Tree-sitter for both.

----

```js
const Foo = require('foo');
//     | <-- ^ Cursor
```
> Now incorrectly marked as `meta.class`

TextMate:
![image](https://user-images.githubusercontent.com/427137/45895713-c39e5100-bd86-11e8-9c5f-b036a00afdb1.png)
Tree-sitter:
![image](https://user-images.githubusercontent.com/427137/45895699-b84b2580-bd86-11e8-87cb-6383fc63eadc.png)

I'd say this is more it is now _correctly_ marked as class, generally when it is a capital first letter, and lower case for the rest it isn't a constant.

----

```js
const foo = require('foo');
//     | <-- ^ Cursor
```
> Now no longer marked as constant, not even variable, just source.js

Textmate:
![image](https://user-images.githubusercontent.com/427137/45895829-1c6de980-bd87-11e8-9978-9f4f8a5e23b4.png)
Tree-sitter:
![image](https://user-images.githubusercontent.com/427137/45895853-2d1e5f80-bd87-11e8-8efb-0c95944dac01.png)

This definitely looks like a bug to me at least, thanks!

----

```js
const bar = {};
bar.FOO = 42;
//   | <-- ^ Cursor
```
> the `FOO` bit was marked as constant property, now just generic object property

TextMate:
![image](https://user-images.githubusercontent.com/427137/45895985-9605d780-bd87-11e8-9c15-a56ccd5c991f.png)
Tree-sitter:
![image](https://user-images.githubusercontent.com/427137/45895968-8b4b4280-bd87-11e8-862a-7a9246f5dd0c.png)

Looks like a regression to me as well, thanks!

**Comment by Arcanemagus** [comment] 2018-09-21 17:28
As a note, it looks like _some_ of this was fixed/changed in https://github.com/atom/language-javascript/pull/587.

**Comment by adamreisnz** [comment] 2018-09-21 19:59
Thanks for confirming.

> I'd say this is more it is now correctly marked as class, generally when it is a capital first letter, and lower case for the rest it isn't a constant.

Yes, this generally holds true, but not in all cases. There will be some cases where the capitalised output of a 3rd party package is a singleton service instead of a class. For example, when using destructured importing like this, you have little control over how to name the variable:

```js
const {FooService, BarService} = require('some-services');
```

I know you can do something like `const {FooService: fooService}` but that's quite frankly a bit of a time waster and ugly, and `FooService` will still incorrectly be marked as a class.

I can live with this one though.

> With the TextMate behavior, the two occurrences of foo would have two different scopes; the second occurrence would not have the constant.other scope. This would usually result in foo appearing in two different colors, which is really counterproductive to the overall purpose of syntax highlighting.

This is correct, and this is exactly what happens. And while I agree that this behaviour is not ideal, I disagree with the solution being to just strip out constant marking altogether. Because while we have gotten used to the constants being coloured like plain variables further down the track in the code, it was still great to at least see clearly when a variable is defined, that it was a constant and not a plan mutable variable:

```js
const foo = 2;
let bar = 3;
```

This made it clear at a glance with visual grepping that you're defining a constant, and not a mutable variable. Making them the same colour is reversing that and making it harder to distinguish. So despite the shortcomings of current syntax highlighting to be able to "keep track" of a constant further down the line, I don't think it's a good idea to get rid of it.

Same holds for `foo.BAR`. Having the `BAR` marked as a constant property really aids in finding constants like this in our code. We use structures our constants like that extensively, e.g.:

```js
/**
 * Area states
 */
module.exports = {
  MODE: 'mode',
  ERROR: 'error',
  EMPTY: 'empty',
  SETUP: 'setup',
  EVENT: 'event',
  OVERRIDE: 'override',
  UNKNOWN: 'unknown',
};
```

Later, it's very convenient to have syntax highlighting identify them as constants, when used like:

```js
if (states.includes(areaStates.MODE, areaStates.EVENT) { ... }
```

Once again if `areaStates.mode` and `areaStates.MODE` get the same highlighting, it reduces visual grepping and the ability to quickly distinguish constant and variable properties on an object.

**Comment by maxbrunsfeld** [comment] 2018-09-21 20:16
Yeah, applying the `constant.other.property` scope to all-caps properties like `foo.BAR` would be an easy change, and it actually doesn't have the problem that I mentioned about inconsistency; we can definitely highlight those in a consistent manner.

Want to open a PR adding this scope @adamreisnz? The API is described in this [section of the flight manual](https://flight-manual.atom.io/hacking-atom/sections/creating-a-grammar/#text-based-mappings). You could pretty much copy what we [do for regular `identifier` nodes](https://github.com/atom/language-javascript/blob/df7a049ec5b6e866b1686c561ba8d8bb7c0de0c5/grammars/tree-sitter-javascript.cson#L96-L99) and apply the same thing to [`property_identifier`](https://github.com/atom/language-javascript/blob/df7a049ec5b6e866b1686c561ba8d8bb7c0de0c5/grammars/tree-sitter-javascript.cson#L52) nodes.

**Comment by adamreisnz** [comment] 2018-09-21 21:36
@maxbrunsfeld I'd love to, but as it is my time is spread between our own startup, several other open source projects and 3 freelance projects, so I can't really spread myself any thinner at this stage :(

I've disabled the Tree Sitter parser for now which brings back the expected behaviour for us, as long as this setting is available I'm happy to wait until the fixes/improvements you describe make it in.

It'd be great to finally properly differentiate constants and variables throughout the code.

**Comment by maxbrunsfeld** [comment] 2018-11-09 21:56
All-caps (constant) properties are now highlighted the same way they used to be. I'm going to close this out, since the remaining changes from the TextMate highlighting are intentional.

**Closed by maxbrunsfeld** 2018-11-09 21:56 UTC
Labels: bug, regression, tree-sitter

**Comment by adamreisnz** [comment] 2018-11-26 18:11
This is still an issue in Atom 1.34 nightly.

![image](https://user-images.githubusercontent.com/490562/49033283-97360380-f213-11e8-9003-2eadcd1ac48e.png)

**Comment by FelixVicis** [comment] 2019-04-24 19:56
This is still occuring in 1.36.0

I've been sitting at an older version waiting for this to be fixed. This might seem like a small problem from the language parser, however, this is a large problem as a consumer.

Please, until you get the tree parser where you want it, return the highlighting back.

**Comment by Arcanemagus** [comment] 2019-04-24 22:12
Please file a _new_ issue outlining how you believe this isn't correctly being highlighted, making sure you fill out the template, so we can look into it there.

As described in https://github.com/atom/language-javascript/issues/597#issuecomment-437507516 the part of this that was a bug has already been fixed, and the rest is an intentional change as determined by the team.
