### ISSUE TITLE
Long lines with many segments screw up highlighting

### ISSUE THREAD

**Issue by Quicksaver** [atom/language-javascript#443] opened 2016-10-13 15:09 UTC
Example: https://github.com/Quicksaver/Bootstraped-Addon-Backbone/blob/master/resource/modules/utils/Keysets.jsm

Open that file in Atom and make sure its Javascript syntax is highlighted. From line 119 onwards, the highlighting is all screwed up. I can "fix" it by either commenting it out or by adding a new line after ``` 'S',``` and another after ```'/',```. Lines 122 and 127 have similar problems.

**Comment by 50Wliu** [comment] 2016-10-13 16:05
This is a duplicate of atom/atom#1667 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-10-13 16:05 UTC
