### ISSUE TITLE
Object property names not being highlighted/tagged

### ISSUE THREAD

**Issue by joepie91** [atom/language-javascript#421] opened 2016-08-29 21:33 UTC
It seems that object property names are not being recognized and tagged by the syntax highlighter, for some reason. This makes it impossible to style them.

* __OS:__ NixOS (Linux) 16.03, 64-bit
* __Atom version:__ 1.9.9
* __language-javascript version:__ 0.119.0

Illustrated below:

<img src="https://i.imgur.com/X5Ytn2l.png">

Test case:

```javascript
var derp = {
  foo: false,
  bar: "derp"
};
```

(As an aside - the link in your `CONTRIBUTING.md` is dead...)

**Comment by 50Wliu** [comment] 2016-08-30 02:19
This is a duplicate of #287 - feel free to subscribe there for updates.

A PR to fix the CONTRIBUTING.md to point to the one in atom/atom would be appreciated.

**Closed by 50Wliu** 2016-08-30 02:19 UTC
