### ISSUE TITLE
Syntax highlight for regex fails

### ISSUE THREAD

**Issue by mc10** [atom/language-javascript#98] opened 2015-02-03 18:55 UTC
The syntax highlighting for [this regex](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/lib/modules/hosts/imgur.js#L17) fails, but interestingly, it works properly if you remove any characters:

![Screenshot](http://cl.ly/image/332U1X2U0G3f/Image%202015-02-03%20at%2010.53.49%20AM.png)

The line of code is reproduced below:

    hashRe: /^https?:\/\/(?:i\.|m\.|edge\.|www\.)*imgur\.com\/(?:r\/[\w]+\/)*(?!gallery)(?!removalrequest)(?!random)(?!memegen)([\w]{5,7}(?:[&,][\w]{5,7})*)(?:#\d+)?[sbtmlh]?(\.(?:jpe?g|gif|png|gifv))?(\?.*)?$/i,

**Comment by kevinsawicki** [comment] 2015-02-03 18:59
I believe this is a duplicate of https://github.com/atom/atom/issues/1667

**Closed by kevinsawicki** 2015-02-03 18:59 UTC
