### ISSUE TITLE
Incorrect syntax highlighting in comments -  anything ALLCAPS or @atPrefixed gets highlighted

### ISSUE THREAD

**Issue by kevinflo** [atom/language-javascript#151] opened 2015-05-20 23:34 UTC
![screen shot 2015-05-20 at 4 27 23 pm](https://cloud.githubusercontent.com/assets/661291/7738822/a6685e22-ff0d-11e4-9ce8-22b2ff35e1c5.png)

Atom version 0.199.0 on OS X

**Comment by 50Wliu** [comment] 2015-05-20 23:37
Can you reproduce this in safe mode (`atom --safe`)?

**Comment by kevinflo** [comment] 2015-05-20 23:42
I just opened the file with the command `atom --safe TodoStore.js` and the file looks the same to me.

![screen shot 2015-05-20 at 4 39 05 pm](https://cloud.githubusercontent.com/assets/661291/7738929/efb7451a-ff0e-11e4-99e2-a57a8a5a311b.png)

I don't see any indication that atom is now in safe mode though, but I also don't know where to look to check.  Clicking Atom > About Atom now shows it's running version 0.200.0.

**Comment by 50Wliu** [comment] 2015-05-20 23:48
There should be a green square in the lower-left corner of the status bar.
Pretty sure you need to close out all running instances of Atom before opening it up in a different mode (such as safe mode).

**Comment by kevinflo** [comment] 2015-05-20 23:50
Thanks.  Yes, the atom window is in safe mode and the syntax highlighting bug is still present.

**Comment by mnquintana** [comment] 2015-05-20 23:51
`TODO` is highlighted by [language-todo](https://github.com/atom/language-todo) – are any other all-caps words highlighted?

**Comment by 50Wliu** [comment] 2015-05-20 23:51
Probably related to #138 then.

**Comment by 50Wliu** [comment] 2015-07-25 23:46
Cannot reproduce with ALLCAP words other than those in [language-todo](https://github.com/atom/language-todo), and the @-prefixed words are explicitly defined in the Javascript language, so closing this out.

**Closed by 50Wliu** 2015-07-25 23:46 UTC
Labels: bug
