### ISSUE TITLE
Incorrect highlighting for export async function

### ISSUE THREAD

**Issue by wingyplus** [atom/language-javascript#504] opened 2017-04-30 15:20 UTC
export async function apply scope `.variable.other.module.js` for `async` keyword but when use async function, it apply scope `.storage.modifier.async.js`. See in example below:

<img width="803" alt="screen shot 2560-04-30 at 10 20 09 pm" src="https://cloud.githubusercontent.com/assets/484530/25565567/3431bfe4-2df3-11e7-9761-857b0fc361de.png">

**Comment by wolfy1339** [comment] 2018-12-01 00:02
This is a duplicate of another issue, and was deemed to be fixed with tree-sitter

**Comment by rsese** [comment] 2018-12-11 20:35
Thanks for the report @wingyplus and thanks for the reference @wolfy1339 - closing as a duplicate of https://github.com/atom/language-javascript/issues/563.

**Closed by rsese** 2018-12-11 20:35 UTC
Labels: bug
