### ISSUE TITLE
Babelify inline JavaScript map causes Atom to freeze

### ISSUE THREAD

**Issue by anthwinter** [atom/language-javascript#306] opened 2016-01-18 17:29 UTC
Using language-javascript v0.104.0 and atom v1.4.0 on Windows 8. I have problems when I open my compiled javascript file after it has been through babel / browserify.

I found that when I turned off debug mode in browserify (which puts the inline map at the end of the JS file) it worked OK.

If I leave the inline map in the file and then disable only language-javascipt. It is OK.

The inline map is base64 encoded.

**Comment by 50Wliu** [comment] 2016-01-19 00:26
Is there any chance you can share the file (and make sure you can reproduce the issue using `atom --safe`)?  If not, can you try to find a minimal reproduction case?  Thanks!

**Comment by anthwinter** [comment] 2016-01-19 09:38
Hi, having made a test case, it seems to be down to the size of the file (which increases the size of the source map, which I think might be the culprit).

I have attached a test file that causes atom to stop responding. 

The original file also has the issue in safe mode, as does this test file.

[test-compiled.zip](https://github.com/atom/language-javascript/files/95617/test-compiled.zip)

**Comment by mnquintana** [comment] 2016-01-19 13:20
Thanks for the update! After taking a look at the file, I think this is a duplicate of https://github.com/atom/atom/issues/979 – feel free to subscribe there for updates.

**Closed by mnquintana** 2016-01-19 13:20 UTC
Labels: more-information-needed, needs-reproduction
