### ISSUE TITLE
Failed to load a language-javascript package grammar

### ISSUE THREAD

**Issue by FirixQ** [atom/language-javascript#509] opened 2017-05-22 21:00 UTC
Steps to reproduce:

1. Start Atom

**Atom**: 1.17.0 ia32
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [language-javascript](https://github.com/atom/language-javascript) package 0.126.1

### Stack Trace

Failed to load a language-javascript package grammar

```
At ENOENT: no such file or directory, open 'C:\Users\Matt\AppData\Local\atom\app-1.17.0\resources\app\node_modules\language-javascript\grammars\regular expression replacement (javascript).json' in C:\Users\Matt\AppData\Local\atom\app-1.17.0\resources\app\node_modules\language-javascript\grammars\regular expression replacement (javascript).json

Error: ENOENT: no such file or directory, open 'C:\Users\Matt\AppData\Local\atom\app-1.17.0\resources\app\node_modules\language-javascript\grammars\regular expression replacement (javascript).json'
    at Error (native)
  at ~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/language-javascript/grammars/regular expression replacement (javascript).json:1:1
```

### Commands

```
```

### Non-Core Packages

```
autoclose-html 0.23.0 
script 3.15.0 
```

**Comment by 50Wliu** [comment] 2017-05-23 17:54
Closing as a duplicate of atom/language-java#94.  Reinstalling should fix the issue.

**Closed by 50Wliu** 2017-05-23 17:54 UTC
