### ISSUE TITLE
Arrow function single argument without parenthesis

### ISSUE THREAD

**Issue by KSXGitHub** [atom/language-javascript#292] opened 2015-12-25 07:01 UTC
```javascript
	var arrow = args => 1234; // not works
	var arrow = (args) => 1234; // works
```

![image](https://cloud.githubusercontent.com/assets/11488886/12000813/ee1c6b2e-ab0f-11e5-81bc-effac1423237.png)

I wish that, in the first line, `arrow` is marked as a function and `args` is marked as a parameter.

**Comment by MaximSokolov** [comment] 2015-12-25 08:12
Duplicate of #193

**Comment by 50Wliu** [comment] 2015-12-25 16:52
Thanks @MaximSokolov!

**Closed by 50Wliu** 2015-12-25 16:52 UTC
