### ISSUE TITLE
highlighting long regular expressions

### ISSUE THREAD

**Issue by fixmycode** [atom/language-javascript#85] opened 2015-01-04 15:39 UTC
In version 0.165.0 over OSX, if I define a long regular expression variable, like:

    var re = /(.+)\n(.+)\nCard No.: (\S+)  Rarity: (\S+)\nColor: (\S+)   Side: (\S+)  (\S+)\nLevel: (\d+)   Cost: (\d+)   Power: (\d+)   Soul: (\d+)\nTrait 1: ((\S+) \(([^\(\)]+)\)|None)      Trait 2: ((\S+) \(([^\(\)]+)\)|None)\nTriggers: ([^\n]+) ?\nFlavor: ([\S\s]*)\nTEXT: ([\S\s]*)/;

the editor keep using the blackslash class highlight for the rest of the document. It also happens that part of the line stays outside the line span:

![screen shot 2015-01-04 at 12 32 51 pm](https://cloud.githubusercontent.com/assets/705903/5606432/61136084-940e-11e4-9ba2-9dcfeebf8690.png)

this breaks the highlighting for the rest of the document:

![screen shot 2015-01-04 at 12 33 22 pm](https://cloud.githubusercontent.com/assets/705903/5606437/8a0aab8c-940e-11e4-8c10-9edea4c47ae0.png)

**Comment by izuzak** [comment] 2015-01-04 19:31
I believe this is a duplicate of atom/atom#1667 where the issue is that the line is too long and colorization stops/breaks at a certain token limit (currently, 100). Please subscribe to atom/atom#1667 for updates about this.

**Closed by izuzak** 2015-01-04 19:31 UTC
