### ISSUE TITLE
Incorrect highlighting after default value in destructuring assignment

### ISSUE THREAD

**Issue by KSXGitHub** [atom/language-javascript#470] opened 2016-12-10 13:59 UTC
### Reproduction steps

Write this code

![image](https://cloud.githubusercontent.com/assets/11488886/21073767/4ffa6142-bf1a-11e6-9a41-95e8cf000771.png)

```javascript
const {a, b = 0, c = 1} = obj
const [d, e = 2, f = 3] = arr
const {foo: [g, h = 4, i = 5], bar: [j, k, l]} = objarr
const [{m, n = 6, o = 7}, {p, q, r}] = arrobj
const {foo: s, bar: t = 8, baz: u = 9} = rn
```

### Expectation

All letters (`a` to `u`) are highlighted the same

### Actual Result

`a`, `b`, `d`, `e`, `g`, `h`, `m`, `n`, `s`, `t` are marked as `span.constant.other.js` while the others aren't

**Comment by 50Wliu** [comment] 2016-12-10 15:54
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #196. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2016-12-10 15:54 UTC
