### ISSUE TITLE
Failed to load a language-javascript package grammar

### ISSUE THREAD

**Issue by lucianodesouza** [atom/language-javascript#516] opened 2017-06-07 18:54 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 ia32
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [language-javascript](https://github.com/atom/language-javascript) package 0.126.1

### Stack Trace

Failed to load a language-javascript package grammar

```
At ENOENT: no such file or directory, open 'C:\Users\Luciano\AppData\Local\atom\app-1.17.2\resources\app\node_modules\language-javascript\grammars\regular expressions (javascript).json' in C:\Users\Luciano\AppData\Local\atom\app-1.17.2\resources\app\node_modules\language-javascript\grammars\regular expressions (javascript).json

Error: ENOENT: no such file or directory, open 'C:\Users\Luciano\AppData\Local\atom\app-1.17.2\resources\app\node_modules\language-javascript\grammars\regular expressions (javascript).json'
    at Error (native)
  at ~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/language-javascript/grammars/regular expressions (javascript).json:1:1
```

### Commands

```
     -2:52 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -1:34.8.0 settings-view:check-for-package-updates (atom-pane.pane)
```

### Non-Core Packages

```
autocomplete-clang 0.11.3 
build 0.68.0 
busy 0.7.0 
file-icons 2.1.7 
intentions 1.1.2 
language-ini 1.19.0 
linter 2.1.4 
linter-gcc 0.7.1 
linter-ui-default 1.6.0 
minimap 4.28.2 
platformio-ide 2.0.0-beta.6 
platformio-ide-debugger 1.2.2 
platformio-ide-terminal 2.5.1 
tool-bar 1.1.0 
```

**Comment by rsese** [comment] 2017-06-07 20:10
Closing as a duplicate of https://github.com/atom/language-java/issues/94 but can you try re-installing as mentioned in https://github.com/atom/language-javascript/issues/509 @lucianodesouza?

**Closed by rsese** 2017-06-07 20:10 UTC
