### ISSUE TITLE
BigInt is rendered as error

### ISSUE THREAD

**Issue by hendrysadrak** [atom/language-javascript#578] opened 2018-06-04 11:21 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Here is an example of the error:

```javascript
const veryLargeInt = 100n ** 200n;
```

This without bigint:

```javascript
const veryLargeInt = 100 ** 200;
```

**Comment by thomasjo** [comment] 2018-06-04 13:27
Thanks for the report!

Because _BigInt_ is still a [draft proposal](https://tc39.github.io/proposal-bigint/), I'm going to close this issue. Once the proposal gets accepted, feel free to leave a comment requesting the issue be re-opened, or open a new issue.

**Comment by NN---** [comment] 2018-11-14 15:04
BigInt has already reached Stage3 which means it will be likely to be accepted.

**Comment by michaelficarra** [comment] 2019-11-04 22:29
@thomasjo BigInts still aren't supported by this project, though they are officially part of the language now. See https://tc39.es/ecma262/#sec-bigint-objects. Please re-open.

**Comment by thomasjo** [comment] 2019-11-05 10:06
@michaelficarra I'm no longer involved in the Atom project, so I cannot really champion for this issue getting resolved. I'll reopen it however, in hopes that someone might submit a PR to resolve it.

**Comment by lkashef** [comment] 2019-11-12 20:23
There is a PR that seems to fix this issue https://github.com/atom/language-javascript/pull/588

**Comment by lkashef** [comment] 2019-11-19 22:26
This issue is no longer reproducible, it seems that https://github.com/tree-sitter/tree-sitter-javascript/pull/93 fixed the  issue, if you are able to reproduce, please feel free to open a new issue with the proper template and reproduction steps.

**Comment by michaelficarra** [comment] 2019-11-19 22:41
GitHub linguist points to this repository as the syntax highlighting provider for JavaScript: https://github.com/github/linguist/blob/master/vendor/README.md

They currently reference d66821651bd97279e03c4285269aea2f283a0017, or version `0.132.0`, as a dependency. @lkashef  Are you saying that support for BigInt was added between then and the latest release, `0.133.1`, and if they bump the version, they will get that support?

**Comment by lkashef** [comment] 2019-11-19 23:45
Hey @michaelficarra, you are right [atom/language-javascript](https://github.com/atom/language-javascript) is the syntax highlighting provider in atom for Javascript and this repository depends on [tree-sitter/tree-sitter-javascript](https://github.com/tree-sitter/tree-sitter-javascript).

The `BigInt` support was added to `tree-sitter-javascript` in [v0.13.10](https://github.com/tree-sitter/tree-sitter-javascript/compare/v0.13.10...master) in 18 December 2018, on the next day we bumped `tree-sitter-javascript` version in [atom/language-javascript](https://github.com/atom/language-javascript/compare/v0.129.18...v0.129.19-0), and [atom stable v1.33.1](https://github.com/atom/atom/releases/tag/v1.33.1) was released on the same day with the up-to-date `atom/language-javascript` version 0.129.19.

Now, if you are able to reproduce this error following the steps instructed in the issue template, we can definitely take a look.

**Comment by Aerijo** [comment] 2019-11-19 23:49
@lkashef They are referring to an different project that depends on the TextMate grammar specifically. AFAIK, Atom policy is to only support Tree-sitter when it exists, and encourage anyone depending on the TextMate grammar to maintain their own fork.

**Comment by lkashef** [comment] 2019-11-20 14:03
@Aerijo Based on that PR https://github.com/atom/language-javascript/pull/588, I think the author is referring to Github since it uses the same atom's package to provide syntax highlighting for javascript. So it seems valid to me, I was just missing the context.

**Comment by lkashef** [comment] 2019-11-21 16:17
Fixed by https://github.com/atom/language-javascript/pull/588

**Closed by lkashef** 2019-11-21 16:17 UTC
Labels: blocked, d ⬇️, i ⬇️, triaged, v ⬆️
