### ISSUE TITLE
Crashes if the project has large js files.

### ISSUE THREAD

**Issue by roylee17** [atom/language-javascript#387] opened 2016-07-29 04:38 UTC
Atom 1.8.0

I'm trying to follow through an react tutorial, and Atom hangs/crahes after few second when I browse the following file.

https://github.com/learncodeacademy/react-js-tutorials/blob/master/1-basic-react/src/client.min.js

**Comment by 50Wliu** [comment] 2016-07-30 15:45
This is a duplicate of atom/atom#979 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-07-30 15:45 UTC
