### ISSUE TITLE
Some content incorrectly rendered in italics in v1.40.0

### ISSUE THREAD

**Issue by aviatesk** [atom/language-javascript#657] opened 2019-08-14 20:05 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

After updating to v1.40.0, characters in some JavaScript files get rendered in italic and look funny.

### Steps to Reproduce

1. Create and open a file below:

> Example goto.js

```js
/** @babel */

import { client } from '../connection'
import modules from './modules'
import { isValidScopeToInspect } from '../misc/scopes'
import { getWord, isValidWordToInspect, wordRegex } from '../misc/words'

const methods = client.import('methods')

class Goto {
  activate (ink) {
    this.ink = ink
  }

  /**
   * Returns `true` if Julia-client backend is running and ink is being consumed
   */
  isClientAndInkReady () {
    return client.isActive() && this.ink !== undefined
  }

  gotoSymbol () {
    if (!this.isClientAndInkReady()) return

    const editor = atom.workspace.getActiveTextEditor()
    const { word } = getWord(editor)
    if (!isValidWordToInspect(word)) return

    // Use current module of the `editor`
    const currentModule = modules.current()
    const module = currentModule ? currentModule : 'Main'

    methods({ word: word, mod: module }).then(symbols => {
      if (symbols.error) return
      this.ink.goto.goto(symbols, {
        pending: atom.config.get('core.allowPendingPaneItems')
      })
    })
  }

  provideHyperclick () {
    const getSuggestionForWord = async (textEditor, text, range) => {
      // If Julia is not running, do nothing
      if (!this.isClientAndInkReady()) return

      // If the scope at `bufferPosition` is not valid code scope, do nothing
      const bufferPosition = range.start
      if (!isValidScopeToInspect(textEditor, bufferPosition)) return
      // Check the validity of code to be inspected
      if (!isValidWordToInspect(text)) return

      const { main, sub } = await modules.getEditorModule(textEditor, bufferPosition)
      const module = main ? (sub ? `${main}.${sub}` : main) : 'Main'

      return new Promise((resolve, reject) => {
        methods({ word: text, mod: module }).then(symbols => {
          // If the `methods` call fails or there is no where to go to, do nothing
          if (symbols.error || symbols.items.length === 0) {
            reject(null)
          }
          resolve({
            range: range,
            callback: () => {
              setTimeout(() => {
                this.ink.goto.goto(symbols, {
                  pending: atom.config.get('core.allowPendingPaneItems')
                })
              }, 5)
            }
          })
        })
      })
    }

    return {
      providerName: 'julia-client-hyperclick-provider',
      priority: 100,
      grammarScopes: atom.config.get('julia-client.juliaSyntaxScopes'),
      wordRegExp:  new RegExp(wordRegex, "g"),
      getSuggestionForWord
    }
  }
}

export default new Goto()
```

**Expected behavior:**

Only L1 should be in italic (at least this is the behavior before v1.40.0)

**Actual behavior:**

L2-L53 are rendered in italic

*Edit by @rsese: I see the issue but with different line numbers https://github.com/atom/language-javascript/issues/657#issuecomment-521416539*

**Reproduces how often:**

Always

### Versions

> atom --version

```bash
Atom    : 1.40.0
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
```

> apm --version

```bash
apm  2.4.2
npm  6.2.0
node 10.2.1 x64
atom 1.40.0
python 3.7.1
git 2.22.0.windows.1
visual studio
```

**Comment by rsese** [comment] 2019-08-14 20:59
Thanks for the report - I don't see this behavior on macOS 10.14.6 with 1.40.0 but on Windows 10 I see similar behavior though not the exact same line numbers:

* On the initial paste of your sample content, lines 1 through 6  are italic.
* If I close and reopen the file, lines 1 through 29 are italic.
* With the file open, if I run `Window: Reload` the file looks ok (though shows the same behavior as above if I close and reopen).

I also noticed that this doesn't seem to reproduce on 1.41.0-beta0 however.

**Comment by rsese** [comment] 2019-08-14 21:38
When not rendered in italics:

![js-no-italics](https://user-images.githubusercontent.com/734194/63058192-b663e680-beb1-11e9-9feb-e06e34b40099.png)

Then after closing/reopening the file and some lines are incorrectly rendered in italics:

![js-italics](https://user-images.githubusercontent.com/734194/63058277-eb703900-beb1-11e9-922d-0a1b9e04b856.png)

**Comment by Aerijo** [comment] 2019-08-14 22:49
I’m guessing the fixes for this issue were not back ported https://github.com/atom/atom/issues/19582

**Comment by rsese** [comment] 2019-08-15 21:02
Ahh thanks @Aerijo, forgot about that one :+1:  

Like in https://github.com/atom/atom/issues/19582, this doesn't seem to be an issue with all files but if this is impacting your workflow a lot @aviatesk, this is fixed in the [beta release](https://atom.io/beta) if you want to give that a try (you can run stable and beta side-by-side on Windows now).

**Comment by aviatesk** [comment] 2019-08-16 11:31
Thanks for the fix @Aerijo !

@rsese So I'm just okay if you close this issue since it gonna be fixed anyway in the future releases :)

> this is fixed in the beta release if you want to give that a try (you can run stable and beta side-by-side on Windows now).
That's so cool too !

**Comment by rsese** [comment] 2019-08-19 21:16
Sounds good @aviatesk - since this is fixed in beta, we'll go ahead and close for now but we can reopen if a number of people run into this on the current stable.

**Closed by rsese** 2019-08-19 21:16 UTC
Labels: tree-sitter, triaged, windows
