### ISSUE TITLE
Invalid parenthesis highlighting when using comment

### ISSUE THREAD

**Issue by Xalbi** [atom/language-javascript#383] opened 2016-06-24 09:50 UTC
Incorrect highlighting parenthesis when using comment 

![image](https://cloud.githubusercontent.com/assets/13153320/16334532/c8476ee0-3a01-11e6-83d1-091a60734f21.png)

**Comment by 50Wliu** [comment] 2016-06-24 17:37
This is a duplicate of atom/bracket-matcher#78 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-06-24 17:37 UTC
