### ISSUE TITLE
Template strings with two forward slashes breaks syntax highlighting

### ISSUE THREAD

**Issue by mneumark** [atom/language-javascript#569] opened 2018-04-12 00:03 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The following breaks the syntax highlighting:
```js
const foo = `stuff ${hello}// more stuff`
```

### Steps to Reproduce

1. Open a new editor window with Javascript highlighting turned on.
2. Create a template string with a variable `${ }` in it.
3. after the final `}` put two forward slashes.

**Expected behavior:** Treat the two forward slashes as part of the string. Syntax highlighting continues in the file.

**Actual behavior:** The two forward slashes confuse everything presumably because it thinks its a comment. The rest of the file does not seem to turn into a comment however; it just stops syntax highlighting for the rest of the file.

**Reproduces how often:** 100% consistent

### Versions

Atom    : 1.25.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.1
python 2.7.10
git 2.15.1

### Additional Information

Here is an example of the bug in action:
![screen shot 2018-04-11 at 5 01 59 pm](https://user-images.githubusercontent.com/8795693/38649197-20a95708-3daa-11e8-9a9b-49f5938427dd.png)

**Comment by Arcanemagus** [comment] 2018-04-12 01:49
Thanks for taking the time to contribute!

I'm guessing that you have enabled the experimental Tree-sitter parsers, assuming that is the case this is a duplicate of https://github.com/tree-sitter/tree-sitter-javascript/issues/67. You may want to subscribe there for updates. If you _haven't_ enabled this please let us know!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-04-12 01:49 UTC

**Comment by mneumark** [comment] 2018-04-12 16:04
Nice call. Thanks for the information.
