### ISSUE TITLE
Ternary operator and javascript keywords

### ISSUE THREAD

**Issue by peduxe** [atom/language-javascript#173] opened 2015-07-23 04:32 UTC
![Example](http://i.imgur.com/5EqowMJ.png)
Just the second asignment is covered with syntax highlighting, the behaviour happens too if they're reversed.

**Comment by 50Wliu** [comment] 2015-07-24 00:52
Duplicate of #93, please subscribe there for updates.

**Closed by 50Wliu** 2015-07-24 00:52 UTC
