### ISSUE TITLE
Paren in string is being improperly matched with function paren

### ISSUE THREAD

**Issue by ahayschi** [atom/language-javascript#166] opened 2015-07-02 22:48 UTC
I've noticed that if you have a string containing a paren that is inside a function, that paren will match with the opening paren of that function in JavaScript files. The matching error happens with both single and double quotes. I've attached a screenshot with an example. 

This isn't a critical issue, of course, but it should be documented? 

![zmq-bidirect-msg_js_-__users_alex_code_-_atom](https://cloud.githubusercontent.com/assets/4583084/8489544/f8df93e6-20e1-11e5-8669-beb8b167b893.png)

**Comment by ahayschi** [comment] 2015-07-02 23:00
Sorry, should this be an issue on atom/bracket-matcher instead?

**Comment by 50Wliu** [comment] 2015-07-02 23:50
This is a duplicate of atom/bracket-matcher#78.  Please subscribe there for updates.

**Closed by 50Wliu** 2015-07-02 23:50 UTC
