### ISSUE TITLE
Feature request - disable snippet.

### ISSUE THREAD

**Issue by benpptung** [atom/language-javascript#529] opened 2017-08-20 15:51 UTC
Hi, thank you for this package. :)

I am wondering if this package can add feature to disable some or all snippets.
I've found many snippets considered as `default` snippets coming from this package, 
e.g. `inspect`, `prom`, `req`...etc.

I've tried to override them, but it cannot fix every situation. 
For example, the `prom`, I always trigger it but actually I want to type `prototype`.
it also happened on other snippets..

It would be appreciated if there is anyway to disable them. Thank you :)

**Comment by 50Wliu** [comment] 2017-08-21 22:57
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/snippets#55. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-08-21 22:57 UTC
