### ISSUE TITLE
Syntax highlighting breaks for regexes >512 characters

### ISSUE THREAD

**Issue by apeiron** [atom/language-javascript#91] opened 2015-01-17 02:48 UTC
It's pathological, I'll admit. But it's also real code people write (it's on github, even), and the editor should handle it gracefully. 

![Pathologically long regex synhi fail](http://i.imgur.com/ZiI2MlW.png)

**Comment by lee-dohm** [comment] 2015-01-17 03:20
This is a known issue. Atom currently only highlights the first 100 tokens per line.

This is a duplicate of atom/atom#1667. Please subscribe there for updates.

**Closed by lee-dohm** 2015-01-17 03:20 UTC
