### ISSUE TITLE
Odd highlighting behaviour after long array definitions

### ISSUE THREAD

**Issue by giacecco** [atom/language-javascript#350] opened 2016-04-07 09:42 UTC
Running Atom 1.6.2 on Fedora 23. Atom highlights correctly the syntax of the simple JavaScript code below:

```
// From https://en.wikipedia.org/wiki/RIS_(file_format)#Tags */
var VALID_RIS_TAGS = [ 'TY', 'A1', 'A2', 'A3', 'A4', 'AB', 'AD', 'AN', 'AU', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'CA','CN' ];

var file = fs.readFileSync(path.join(__dirname, argv.in), { 'encoding': 'utf8' });
``` 

![2016-04-07-103902_1054x183_scrot](https://cloud.githubusercontent.com/assets/303693/14347078/0b2529ec-fcad-11e5-8d2b-5feb5378cc7b.png)

... but then I add a space towards the end of the long array, and see what happens:

![2016-04-07-103148_1053x194_scrot](https://cloud.githubusercontent.com/assets/303693/14346850/0986ca1a-fcac-11e5-8883-236c52ed50aa.png)

The workaround is simply splitting the long line:

![2016-04-07-104439_898x254_scrot](https://cloud.githubusercontent.com/assets/303693/14347251/f6d74460-fcad-11e5-98aa-785bedf49c76.png)

Hope documenting this was useful.

**Comment by 50Wliu** [comment] 2016-04-07 13:51
This is a duplicate of atom/atom#1667 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-04-07 13:51 UTC
