### ISSUE TITLE
constructor property name breaks highlighting

### ISSUE THREAD

**Issue by AndreasMadsen** [atom/language-javascript#435] opened 2016-09-18 12:21 UTC
The following code highlights wrong. 

```js
const root = new Node({ constructor: { name: 'root' } });
const stateMap = new Map();
```

![skaermbillede 2016-09-18 kl 14 17 36](https://cloud.githubusercontent.com/assets/505333/18615598/b5b4568e-7daa-11e6-8569-951b7a3c8550.png)

This appears to be because of the property name `constructor`, thus it could be related to #425. However I don't think so, because if I use a different keyword like `new` it highlights fine.

```js
const root = new Node({ new: { name: 'root' } });
const stateMap = new Map();
```

![skaermbillede 2016-09-18 kl 14 19 50](https://cloud.githubusercontent.com/assets/505333/18615608/08ccc4dc-7dab-11e6-8c6b-bb218e831c9d.png)

**Comment by 50Wliu** [comment] 2016-09-18 15:43
Closing as a duplicate of #334.

**Closed by 50Wliu** 2016-09-18 15:43 UTC
