### ISSUE TITLE
Syntax highlighting for language-todo scopes dooesn't work with tree-parser grammar

### ISSUE THREAD

**Issue by jonboiser** [atom/language-javascript#667] opened 2019-12-19 21:34 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

special words that are supposed to be syntax highlighted by the built-in [language-todo](https://github.com/atom/language-todo) are not syntax highlighted when using Tree-Sitter.

Screenshots are using the Dracula theme, which gives these words a blue color and italicizes them

**Using Tree-Sitter**
![Screen Shot 2019-12-19 at 1 32 53 PM](https://user-images.githubusercontent.com/10248067/71211524-2b7e6880-2264-11ea-8de9-cac98fc8c814.png)

**Not Using Tree-Sitter**
![Screen Shot 2019-12-19 at 1 33 03 PM](https://user-images.githubusercontent.com/10248067/71211529-2faa8600-2264-11ea-8009-4047cf53fb28.png)

### Steps to Reproduce

1. Create a JS file with something like `// TODO fix me`
2. In Settings > Editor Menu, uncheck "Use Tree Sitter Parsers"
3. Refresh the editor
3. In your JS file buffer, `TODO` will be syntax highlighted (and given the correct css classes for `storage.class.type.todo` or something like that
1. In Settings > Editor Menu, check "Use Tree Sitter Parsers"
3. Refresh the editor
3. In your JS file buffer, `TODO` _will not_ be syntax highlighted 

**Expected behavior:**

When viewing a JS file with Tree-Sitter parsers enabled, the special tokens highlighted by `language-todo` are highlighted

**Actual behavior:**

No syntax highlighting

**Reproduces how often:**

100%

### Versions

Atom    : 1.42.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0

MacOS 10.15.2

**Comment by lee-dohm** [comment] 2020-01-06 17:42
Thanks for contributing!

We noticed that this is a duplicate of https://github.com/atom/language-todo/issues/82. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2020-01-06 17:42 UTC
Labels: triaged
