### ISSUE TITLE
Opening a minified js-file freezes the editor

### ISSUE THREAD

**Issue by Duncank** [atom/language-javascript#492] opened 2017-02-15 16:11 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

On opening a file that contains minified js, the file opens without syntax highlighting and the editor freezes. After 30 seconds a "editor is not responding"-message will appear with the option to "keep waiting" or close the editor. Keep waiting never fixes it, just gives a new alert after 30 seconds or so.
It doesn't matter if the javascript code is inline in an html-file or in a .js-file of it's own.

### Steps to Reproduce

1. Download plugins.txt and rename to plugins.js. Open the file which contains a couple of minified javascript plugins. Or open any other file with minified js in it.
[plugins.txt](https://github.com/atom/language-javascript/files/777554/plugins.txt)

**Expected behavior:**
File opens, syntax highlighting kicks in and I can edit the file.

**Actual behavior:**
File opens without syntax highlighting and editor freezes.

**Reproduces how often:**
100% of the time.

### Versions
Atom 1.14.2
Electron 1.3.13
Chrome: 52.0.2743.82
Node: 6.5.0
Windows 10, 64bit

When I disable the "language-javascript" package I can edit the file, but there is no syntax highlighting etc.

**Comment by 50Wliu** [comment] 2017-02-15 16:15
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/atom#979. You may want to subscribe there for updates. We are working on increasing minified file performance in atom/atom#13820.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-02-15 16:15 UTC
