### ISSUE TITLE
Creating object literals de-indents the curly brackets.

### ISSUE THREAD

**Issue by Nikita240** [atom/language-javascript#95] opened 2015-01-22 11:44 UTC
![image](https://cloud.githubusercontent.com/assets/6479817/5855060/e09a9a24-a1e8-11e4-9a63-63033625b2f9.png)

I press the `{` key:

![image](https://cloud.githubusercontent.com/assets/6479817/5855072/fce9cd9e-a1e8-11e4-93d0-7f380de32a67.png)

It shouldn't be de-indenting  the curly bracket. In fact, it would be preferred to indent it:

![image](https://cloud.githubusercontent.com/assets/6479817/5855040/b3ea005a-a1e8-11e4-81b6-35c0dafb4e5d.png)

**Comment by Nikita240** [comment] 2015-01-22 11:50
Also, if I manually indent the curly brackets, then place a comma to start the list, it de-indents them again.

![image](https://cloud.githubusercontent.com/assets/6479817/5855115/72d450c4-a1e9-11e4-8fed-7ff9c0a3376a.png)

![image](https://cloud.githubusercontent.com/assets/6479817/5855128/926db556-a1e9-11e4-90a7-7b43abd4823e.png)

All in all it is EXTREMELY annoying. Just to write something as simple as this:

![image](https://cloud.githubusercontent.com/assets/6479817/5855148/bd6542ce-a1e9-11e4-97fb-4d244e9d1621.png)

I have to re-indent FIVE, I repeat, FIVE times.

**Comment by kevinsawicki** [comment] 2015-01-22 19:21
Dupe of https://github.com/atom/language-javascript/issues/77

This should be fixed in the next Atom release.

**Closed by kevinsawicki** 2015-01-22 19:21 UTC

**Comment by Nikita240** [comment] 2015-01-23 04:57
Updating to v0.55 resolved the issue.

+1
