### ISSUE TITLE
Grammar stop tokenizing on some long lines

### ISSUE THREAD

**Issue by basarat** [atom/language-javascript#229] opened 2015-09-29 04:12 UTC
Here is a sample line : 

```js
let x = ['accept', 'alt', 'autocomplete', 'autofocus', 'checked', 'dirname', 'disabled', 'form', 'formaction', 'formenctype', 'formmethod', 'formnovalidate', 'formtarget', 'height', 'list', 'max', 'maxlength', 'min', 'minlength', 'multiple', 'name', 'pattern', 'placeholder', 'readonly', 'required', 'size', 'src', 'step', 'type', 'value', 'width'];
```

Screenshot of error : 

![image](https://cloud.githubusercontent.com/assets/874898/10155125/ff1457de-66b3-11e5-8080-d2c7498749de.png)

near column `245`

Refs https://github.com/TypeStrong/atom-typescript/issues/623#issuecomment-143932326

**Comment by mnquintana** [comment] 2015-09-29 04:18
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/1667 - please subscribe there for updates.

**Closed by mnquintana** 2015-09-29 04:18 UTC
